name: Build and deploy Node.js app to Azure Web App - backendend-graph-app-d

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: List all files
        run: |
          echo "Listing all files in repository:"
          find . -type f

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm ci
          npm run build --if-present
          npm run test --if-present
        env:
          APP_API_KEY: ${{ secrets.APP_API_KEY }}
          NEO4J_URI: ${{ secrets.NEO4J_URI }}
          NEO4J_USERNAME: ${{ secrets.NEO4J_USERNAME }}
          NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
          MICROSOFT_TENANTID: ${{ secrets.MICROSOFT_TENANTID }}
          MICROSOFT_CLIENTID: ${{ secrets.MICROSOFT_CLIENTID }}
          MICROSOFT_SECRETVALUE: ${{ secrets.MICROSOFT_SECRETVALUE }}

      - name: Prune development dependencies
        run: npm prune --production

      - name: Archive production artifacts
        run: |
          tar -czvf node-app.tar.gz -C . .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: ./node-app.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: Extract artifacts
        run: tar -xzvf node-app.tar.gz

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'backendend-graph-app-d'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A549A7B21AC54131B90877EEEDA97431 }}
          package: .
